version: "3"
services:
  homeassistant:
    container_name: {{ container.name }}
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
{% if container.proxy is true %}
    networks:
      - proxy
{% endif %}
    restart: unless-stopped

{% if container.proxy is true %}
networks:
  proxy:
    external: true
{% endif %}
