version: "2.1"
services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=UTC
    user: 1000:1000
    volumes:
      - ./data:/var/lib/ntfy
      - ./cache:/var/cache/ntfy
      - ./ntfy:/etc/ntfy
    restart: unless-stopped
    networks:
      - proxy
networks:
  proxy:
    external: true
