version: "3"
services:
  navidorme:
    image: deluan/navidrome:latest
    container_name: {{ container.name }}
    user: {{ container_uid }}:{{ container_gid }}
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_BASEURL: "/"
      FQDN: {{ sh_domain }}
    volumes:
      - ./data:/data
      - nfs_nfs-mp3:/music:ro
{% if container.proxy is true %}
    networks:
      - proxy
networks:
  proxy:
    external: true
{% endif %}
volumes:
  nfs_nfs-mp3:
    external: true

