version: '3'
services:
  wallabag:
    container_name: {{ container.name }}
    image: wallabag/wallabag
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD={{ wallabag_mysql_root_passwd }}
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST="{{ container.name }}-db"
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME={{ wallabag_db_name }}
      - SYMFONY__ENV__DATABASE_USER={{ wallabag_db_user }}
      - SYMFONY__ENV__DATABASE_PASSWORD={{ wallabag_db_passwd }}
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=wallabag@example.com
      - SYMFONY__ENV__DOMAIN_NAME={{ wallabag_domain_name }}
      - SYMFONY__ENV__SERVER_NAME="My Server"
      - SYMFONY__ENV__REDIS_HOST=="{{ container.name }}-redis"

    ports:
      - "9080:80"
    volumes:
      - ./images:/var/www/wallabag/web/assets/images
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    depends_on:
      - {{ container.name }}_db
      - {{ container.name }}_redis

    networks:
{% if container.proxy is true %}
      - proxy
{% endif %}
      - {{ container.name }}-internal
  {{ container.name }}_db:
    container_name: {{ container.name }}-db
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD={{ wallabag_mysql_root_passwd }}
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "--password={{ wallabag_mysql_root_passwd }}"]
      interval: 20s
      timeout: 3s
    networks:
      - {{ container.name }}-internal

  {{ container.name }}_redis:
    container_name: {{ container.name }}-redis
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
    networks:
      - {{ container.name }}-internal
networks:
  {{ container.name }}-internal:
{% if container.proxy is true %}
  proxy:
    external: true
{% endif %}


