version: '3'
services:
  wallabag:
    container_name: wallabag
    image: wallabag/wallabag
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD={{ wallabag_mysql_root_passwd }}
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=wallabag-db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME={{ wallabag_db_name }}
      - SYMFONY__ENV__DATABASE_USER={{ wallabag_db_user }}
      - SYMFONY__ENV__DATABASE_PASSWORD={{ wallabag_db_passwd }}
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=wallabag@example.com
      - SYMFONY__ENV__DOMAIN_NAME={{ wallabag_domain_name }}
      - SYMFONY__ENV__SERVER_NAME="My Server"
      - SYMFONY__ENV__REDIS_HOST=="wallabag-redis"

    ports:
      - "80"
    volumes:
      - ./images:/var/www/wallabag/web/assets/images
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    depends_on:
      - wallabag_db
      - wallabag_redis
    networks:
      - proxy
  wallabag_db:
    container_name: wallabag-db
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD={{ wallabag_mysql_root_passwd }}
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "--password={{ wallabag_mysql_root_passwd }}"]
      interval: 20s
      timeout: 3s
    networks:
      - proxy

  wallabag_redis:
    container_name: wallabag-redis
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
    networks:
      - proxy
networks:
  proxy:
    external: true


