version: "2.1"
services:
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
      - CHECK_FREQUENCY=30
      - PASSWORD={{ podgrab_passwd }} ## Uncomment to enable basic authentication, username = podgrab
    volumes:
      - ./config:/config
      - ./data:/assets
    networks:
      - proxy
    restart: unless-stopped
networks:
  proxy:
    external: true
