version: "3.0"
services:
  memos:
    image: neosmemo/memos:latest
    container_name: {{ container.name }}
    restart: unless-stopped
    volumes:
      - ./data/:/var/opt/memos

{% if container.proxy is true %}
    networks:
      - proxy

networks:
  proxy:
    external: true
{% endif %}
