version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: {{ container.name }}
    environment:
      - AUDIOBOOKSHELF_UID={{ container_uid }}
      - AUDIOBOOKSHELF_GID={{ container_gid }}
    volumes:
      - ./audiobooks:/audiobooks
      - ./podcasts:/podcasts
      - ./config:/config
      - ./metadata:/metadata
    restart: unless-stopped
{% if container.proxy is true %}
    networks:
      - proxy
networks:
  proxy:
    external: true
{% endif %}
