---
version: "2.1"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: {{ container.name }}
    environment:
      - PUID={{ container_uid }}
      - PGID={{ container_gid }}
      - TZ=Europe/Madrid
      - SUBDOMAINS={{ sh_subdomain_duckdns }}
      - TOKEN={{ duckdns_token }}
      - LOG_FILE=false #optional
      #    volumes:
      #      - ./config:/config #optional
    restart: unless-stopped
